export const RECIPE_CATEGORIES = [
  "All",
  "Dinner",
  "Breakfast",
  "Soups, Sides & Appetizers",
  "Drinks",
  "Dessert",
];

export const CORE_RECIPES = [
  {
    id: "taco-rice-skillet",
    title: "Taco Rice Skillet",
    category: "Dinner",
    description: "One-skillet weeknight dinner with ground beef, rice, black beans, and corn topped with melted cheese.",
    servings: 4,
    preptime: "5 min",
    cooktime: "25 min",
    tags: ["Mexican", "Beef"],
    ingredients: [
      "1 lb ground beef (80/20)",
      "1 cup long grain white rice, uncooked",
      "2 cups chicken stock (Better Than Bouillon)",
      "1 can diced tomatoes with green chiles (10 oz)",
      "1 can black beans, drained and rinsed (15 oz)",
      "1 cup corn kernels, frozen or canned",
      "2 tbsp taco seasoning (or 1 packet)",
      "1 cup shredded Mexican cheese blend",
      "2 tbsp neutral oil",
      "Salt and pepper to taste",
      "Optional: sour cream, avocado, jalapeño, cilantro for serving",
    ],
    steps: [
      "Heat oil in a large skillet over medium-high. Add ground beef, break apart, and cook until browned, 5–6 min. Drain excess fat.",
      "Add taco seasoning and stir to coat. Toast 30 seconds.",
      "Add uncooked rice and stir to combine with the beef.",
      "Pour in chicken stock and diced tomatoes. Stir, bring to a boil, then reduce heat to low. Cover and cook 18 min until rice is tender and liquid absorbed.",
      "Stir in black beans and corn. Heat through 2 min.",
      "Top with cheese, cover off heat 1–2 min to melt. Serve from the skillet with desired toppings.",
    ],
    notes: "Make-ahead: cook full skillet, refrigerate up to 4 days. Reheat in skillet with a splash of water. Freezes well up to 3 months.",
  },
  {
    id: "lemon-orzo-chicken",
    title: "Lemon Orzo with Roasted Chicken Thighs",
    category: "Dinner",
    description: "One-pan dinner with crispy-skinned chicken thighs roasted over lemony orzo with spinach and Parmesan.",
    servings: 4,
    preptime: "10 min",
    cooktime: "35 min",
    tags: ["Mediterranean", "Chicken"],
    ingredients: [
      "4 bone-in skin-on chicken thighs",
      "1.5 cups orzo",
      "3 cups chicken stock (Better Than Bouillon)",
      "1 lemon, zested and juiced",
      "4 cloves garlic, minced",
      "1 cup baby spinach",
      "0.5 cup grated Parmesan",
      "2 tbsp butter",
      "2 tbsp olive oil",
      "1 tsp Italian seasoning",
      "Salt and pepper to taste",
    ],
    steps: [
      "Preheat oven to 425°F. Pat chicken dry, season generously with salt, pepper, and Italian seasoning.",
      "Heat olive oil in an oven-safe skillet over medium-high. Sear chicken thighs skin-side down 5–6 min until golden. Flip and sear 2 min more. Transfer to a plate.",
      "In the same skillet, sauté garlic 30 seconds. Add orzo and toast 1–2 min, stirring.",
      "Add stock, lemon zest, and lemon juice. Bring to a simmer. Nestle chicken thighs back in skin-side up.",
      "Transfer skillet to oven. Roast 20–22 min until chicken is cooked through (165°F) and orzo has absorbed most of the liquid.",
      "Remove from oven. Stir in spinach and butter. Top with Parmesan. Rest 5 min before serving.",
    ],
    notes: "One-pan meal. Batch prep: sear chicken on the weekend and refrigerate; finish in oven on weeknight.",
  },
  {
    id: "beef-stroganoff",
    title: "Ground Beef Stroganoff",
    category: "Dinner",
    description: "Creamy weeknight stroganoff with ground beef, deeply browned mushrooms, and egg noodles.",
    servings: 4,
    preptime: "5 min",
    cooktime: "25 min",
    tags: ["Comfort Food", "Beef"],
    ingredients: [
      "1 lb ground beef (80/20)",
      "8 oz egg noodles",
      "8 oz cremini mushrooms, sliced",
      "1 medium yellow onion, diced",
      "3 cloves garlic, minced",
      "1 cup sour cream",
      "1 cup beef stock (Better Than Bouillon)",
      "2 tbsp Worcestershire sauce",
      "1 tbsp Dijon mustard",
      "2 tbsp all-purpose flour",
      "2 tbsp butter",
      "1 tbsp neutral oil",
      "Salt, pepper, fresh parsley for garnish",
    ],
    steps: [
      "Cook egg noodles according to package. Reserve ½ cup pasta water. Drain and set aside.",
      "Heat oil in a large skillet over medium-high. Brown beef, breaking apart, 5–6 min. Season with salt and pepper. Remove to a bowl.",
      "In the same skillet, add butter. Sauté onion 3 min. Add mushrooms and cook until deeply browned, 5–6 min. Add garlic 30 seconds.",
      "Sprinkle flour over vegetables, stir 1 min. Add beef stock and Worcestershire. Bring to a simmer, stirring until thickened, 3 min.",
      "Reduce heat to low. Stir in sour cream and Dijon — do not boil. Return beef to skillet.",
      "Add noodles and toss to combine. Add pasta water to loosen if needed. Season to taste. Garnish with parsley.",
    ],
    notes: "Mushrooms must be deeply browned — don't rush this step. Sour cream will break if boiled.",
  },
  {
    id: "halibut-cilantro-rice",
    title: "Pan-Seared Halibut with Cilantro Lime Rice and Roasted Broccoli",
    category: "Dinner",
    description: "Crispy pan-seared halibut over bright cilantro lime rice with oven-roasted broccoli.",
    servings: 4,
    preptime: "10 min",
    cooktime: "30 min",
    tags: ["Seafood", "Mexican"],
    ingredients: [
      "1.5 lbs halibut fillets",
      "1.5 cups jasmine rice, uncooked",
      "3 cups water",
      "1 head broccoli, cut into florets",
      "1 lime, zested and juiced",
      "0.5 cup fresh cilantro, chopped",
      "3 tbsp olive oil, divided",
      "2 tbsp butter",
      "3 cloves garlic, minced",
      "Salt, pepper, red pepper flakes",
    ],
    steps: [
      "Preheat oven to 425°F. Toss broccoli with 1 tbsp olive oil, salt, and pepper. Roast 20–22 min until crispy edged.",
      "Cook jasmine rice in water with a pinch of salt. When done, fluff with fork and stir in lime zest, lime juice, cilantro, and 1 tbsp olive oil. Season to taste.",
      "Pat fish dry. Season generously with salt and pepper.",
      "Heat remaining olive oil in a stainless skillet over medium-high until shimmering. Add fish presentation-side down. Do not move. Sear 3–4 min until a golden crust forms.",
      "Flip fish. Add butter and garlic. Baste 1–2 min until fish is just cooked through.",
      "Plate rice, top with fish, serve broccoli alongside. Finish with a squeeze of lime.",
    ],
    notes: "Let the fish release naturally from the pan — if it sticks, it's not ready to flip. Halibut preferred over salmon.",
  },
  {
    id: "gazpacho",
    title: "Gazpacho",
    category: "Soups, Sides & Appetizers",
    description: "Cold Spanish tomato soup blended with cucumber, bell pepper, and sherry vinegar. Best made a day ahead.",
    servings: 6,
    preptime: "20 min",
    cooktime: "0 min (chill 2+ hrs)",
    tags: ["Vegetarian", "Spanish"],
    ingredients: [
      "2 lbs ripe Roma tomatoes, cored and roughly chopped",
      "1 English cucumber, roughly chopped",
      "1 red bell pepper, seeded and roughly chopped",
      "0.5 small red onion, roughly chopped",
      "2 cloves garlic",
      "3 tbsp sherry vinegar (or red wine vinegar)",
      "0.25 cup extra virgin olive oil",
      "1 tsp salt",
      "0.5 tsp cumin",
      "Optional garnish: diced cucumber, croutons, drizzle of olive oil",
    ],
    steps: [
      "Combine tomatoes, cucumber, bell pepper, red onion, and garlic in a blender or food processor. Blend until smooth.",
      "Add vinegar, olive oil, salt, and cumin. Blend again.",
      "Taste and adjust — more vinegar for brightness, more salt as needed.",
      "Refrigerate at least 2 hours, overnight is best. Serve cold with desired garnishes.",
    ],
    notes: "Best made 24 hours ahead. Keeps refrigerated up to 5 days. Tomato quality is everything — do not make in winter.",
  },
  {
    id: "pomodoro-crudo",
    title: "Pasta al Pomodoro Crudo",
    category: "Dinner",
    description: "Raw tomato pasta where the heat of freshly drained pasta lightly warms a garlic, basil, and olive oil sauce.",
    servings: 4,
    preptime: "35 min",
    cooktime: "10 min",
    tags: ["Pasta", "Italian"],
    ingredients: [
      "1 lb spaghetti or linguine",
      "2 lbs ripe tomatoes, diced (or halved cherry tomatoes)",
      "4 cloves garlic, thinly sliced",
      "0.5 cup fresh basil leaves, torn",
      "0.25 cup extra virgin olive oil",
      "0.5 tsp red pepper flakes",
      "Salt to taste",
      "Pecorino Romano or Parmesan to finish",
    ],
    steps: [
      "Combine diced tomatoes, garlic, basil, olive oil, red pepper flakes, and 1 tsp salt in a large bowl. Let sit at room temperature 30 min to 1 hour.",
      "Cook pasta in heavily salted boiling water until al dente. Reserve 1 cup pasta water before draining.",
      "Drain pasta and immediately add to the bowl of raw tomatoes. Toss vigorously, adding pasta water a splash at a time until a loose sauce forms.",
      "Season to taste. Serve immediately topped with grated cheese.",
    ],
    notes: "Raw sauce — the heat of the pasta lightly warms the tomatoes. Do not make in winter. Tomato quality is everything.",
  },
  {
    id: "tuscan-chicken-casserole",
    title: "Lighter Tuscan Chicken Casserole",
    category: "Dinner",
    description: "Seared chicken thighs braised with sun-dried tomatoes, baby potatoes, and broccoli finished with Greek yogurt.",
    servings: 5,
    preptime: "10 min",
    cooktime: "40 min",
    tags: ["Italian", "Casserole", "Chicken"],
    ingredients: [
      "2 lbs boneless skinless chicken thighs",
      "1 lb baby potatoes, halved",
      "2 cups broccoli florets",
      "1 cup sun-dried tomatoes in oil, drained and chopped",
      "4 cloves garlic, minced",
      "1 cup chicken stock (Better Than Bouillon)",
      "0.5 cup plain Greek yogurt or light cream",
      "2 tbsp olive oil",
      "1 tsp Italian seasoning",
      "1 tsp smoked paprika",
      "Salt, pepper, fresh parsley",
    ],
    steps: [
      "Preheat oven to 400°F. Season chicken thighs with Italian seasoning, smoked paprika, salt, and pepper.",
      "Heat olive oil in an oven-safe Dutch oven over medium-high. Sear chicken 3–4 min per side until golden. Remove.",
      "Sauté garlic 30 seconds. Add sun-dried tomatoes and potatoes. Pour in chicken stock.",
      "Return chicken to pan. Cover and transfer to oven. Bake 25 min.",
      "Remove from oven. Add broccoli around the chicken. Bake uncovered 10 more min.",
      "Remove chicken. Stir Greek yogurt into the pan sauce. Return chicken. Garnish with parsley and serve.",
    ],
    notes: "Batch prep: sear chicken on weekend, store separately. Assemble and bake on weeknight. Freezes well before adding yogurt.",
  },
  {
    id: "chicken-marsala",
    title: "Chicken Marsala with Cream Cheese Mashed Potatoes",
    category: "Dinner",
    description: "Seared chicken cutlets in a Marsala-mushroom pan sauce over ultra-creamy cream cheese mashed potatoes.",
    servings: 4,
    preptime: "10 min",
    cooktime: "35 min",
    tags: ["Italian", "Chicken"],
    ingredients: [
      "4 boneless skinless chicken breasts, pounded thin",
      "8 oz cremini mushrooms, sliced",
      "0.75 cup Marsala wine, dry — Madeira also excellent",
      "0.5 cup chicken stock (Better Than Bouillon)",
      "2 tbsp all-purpose flour",
      "3 tbsp butter, divided",
      "2 tbsp olive oil",
      "2 cloves garlic, minced",
      "2 lbs Yukon Gold potatoes, cubed",
      "4 oz cream cheese, softened",
      "0.5 cup warm milk or cream",
      "Salt, pepper, fresh parsley",
    ],
    steps: [
      "Boil potatoes in salted water until fork-tender, 15–18 min. Drain. Mash with cream cheese, warm milk, salt, and pepper until smooth. Keep warm.",
      "Season chicken with salt and pepper, dredge lightly in flour.",
      "Heat oil and 1 tbsp butter in a large skillet over medium-high. Sear chicken 4–5 min per side until golden. Remove.",
      "In same skillet, add mushrooms. Cook until deeply browned, 5–6 min. Add garlic 30 seconds.",
      "Deglaze with Marsala, scraping up the fond. Add chicken stock. Simmer 3–4 min until slightly reduced.",
      "Swirl in remaining 2 tbsp butter. Return chicken to pan and coat with sauce. Serve over mashed potatoes, garnished with parsley.",
    ],
    notes: "Mushrooms must be deeply browned before deglazing. Madeira is an excellent Marsala substitute.",
  },
  {
    id: "halibut-white-bean",
    title: "Pan-Seared Halibut over White Bean Puree with Broccolini",
    category: "Dinner",
    description: "Beautifully seared halibut over a silky white bean puree with sautéed broccolini and a lemon-herb baste.",
    servings: 4,
    preptime: "10 min",
    cooktime: "25 min",
    tags: ["Seafood"],
    ingredients: [
      "1.5 lbs halibut fillets",
      "2 cans white cannellini beans, drained and rinsed (15 oz each)",
      "1 bunch broccolini, trimmed",
      "4 cloves garlic, divided",
      "0.5 cup chicken stock (Better Than Bouillon)",
      "3 tbsp olive oil, divided",
      "2 tbsp butter",
      "1 lemon, for juice and zest",
      "1 tsp fresh thyme or rosemary",
      "Red pepper flakes, salt, pepper",
    ],
    steps: [
      "Make white bean puree: heat 1 tbsp olive oil over medium. Sauté 2 cloves garlic 1 min. Add beans and stock. Simmer 5 min. Blend or mash until smooth. Season with salt, pepper, and lemon zest. Keep warm.",
      "Sauté broccolini in a hot skillet with 1 tbsp olive oil until bright green and tender-crisp, 3–4 min. Season and set aside.",
      "Pat halibut dry. Season generously with salt and pepper.",
      "Heat remaining olive oil in a stainless skillet over medium-high until shimmering. Sear halibut presentation-side down 3–4 min without moving.",
      "Flip. Add butter, remaining garlic, and thyme. Baste 1–2 min until just cooked through.",
      "Spoon white bean puree onto plates, top with halibut. Arrange broccolini alongside. Finish with lemon juice and red pepper flakes.",
    ],
    notes: "Don't move the fish until it releases naturally. Bean puree can be made 2 days ahead. Halibut preferred over salmon.",
  },
  {
    id: "scallops-grits",
    title: "Seared Scallops with Cheddar Grits and Wilted Spinach",
    category: "Dinner",
    description: "Dry-packed sea scallops with a deep golden crust over creamy cheddar grits with garlicky wilted spinach.",
    servings: 4,
    preptime: "10 min",
    cooktime: "30 min",
    tags: ["Seafood", "Comfort Food"],
    ingredients: [
      "1.5 lbs large sea scallops (dry-packed)",
      "1 cup stone-ground grits (not instant)",
      "4 cups chicken stock (Better Than Bouillon)",
      "1 cup shredded sharp cheddar",
      "2 tbsp butter, divided",
      "4 cups baby spinach",
      "3 cloves garlic, minced",
      "2 tbsp neutral oil (high smoke point)",
      "0.25 cup dry white wine or chicken stock",
      "Salt, pepper, lemon wedges for serving",
    ],
    steps: [
      "Bring stock to a boil. Whisk in grits with a pinch of salt. Reduce heat to low. Cook 20–25 min stirring frequently until thick and creamy. Stir in cheddar and 1 tbsp butter. Season and keep warm.",
      "Pat scallops very dry with paper towels. Remove side muscle. Season with salt and pepper.",
      "Heat neutral oil in a stainless skillet over high until just smoking. Add scallops with space between them. Do not move. Sear 2 min until a deep golden crust forms.",
      "Flip scallops. Add 1 tbsp butter and baste 1–2 min. Just translucent in center. Remove to a plate.",
      "In same skillet, sauté garlic 30 seconds. Add spinach and wine. Toss until wilted, 1–2 min. Season.",
      "Spoon grits into bowls. Top with spinach and scallops. Serve with lemon wedges.",
    ],
    notes: "Dry-packed scallops only — wet-packed won't sear properly. Scallops must be bone dry. Do not crowd the pan.",
  },
  {
    id: "smash-burgers",
    title: "Smash Burgers",
    category: "Dinner",
    description: "Crispy-edged smash burgers on potato buns with a tangy smash sauce, dill pickles, and American cheese.",
    servings: 4,
    preptime: "10 min",
    cooktime: "15 min",
    tags: ["Beef", "American"],
    ingredients: [
      "1.5 lbs ground beef (80/20)",
      "4 potato buns",
      "4 slices American cheese",
      "0.5 cup mayonnaise",
      "2 tbsp ketchup",
      "1 tbsp yellow mustard",
      "1 tbsp dill pickle brine",
      "1 tsp smoked paprika",
      "1 tsp garlic powder",
      "Toppings: dill pickles, shredded lettuce, sliced onion",
      "Butter for toasting buns",
    ],
    steps: [
      "Mix smash sauce: mayo, ketchup, mustard, pickle brine, paprika, garlic powder. Refrigerate.",
      "Divide beef into 3 oz balls — about 6 total. Do not season yet.",
      "Heat a cast iron or heavy skillet over high for 3–4 min until very hot. Add a small pat of butter.",
      "Place beef balls in pan with space. Immediately smash flat with a spatula or burger press. Season tops with salt and pepper.",
      "Cook 2–3 min until edges are deeply browned and crispy. Flip once. Add cheese immediately. Cook 30 seconds more.",
      "Toast buns in a separate pan with butter. Assemble with sauce, pickles, lettuce, onion.",
    ],
    notes: "Smash immediately when beef hits the pan — it only smashes flat while the fat is still cold. Two thin patties per bun gives the best result.",
  },
  {
    id: "kfc-bowls",
    title: "KFC-Style Mashed Potato Bowls",
    category: "Dinner",
    description: "Comfort food bowls with creamy mashed potatoes, seasoned chicken, corn, gravy, and cheddar cheese.",
    servings: 4,
    preptime: "5 min",
    cooktime: "30 min",
    tags: ["comfort Food", "Chicken"],
    ingredients: [
      "2 lbs Yukon Gold potatoes, peeled and cubed",
      "1 lb boneless skinless chicken thighs, diced",
      "3 tbsp butter",
      "0.5 cup warm cream or milk",
      "1 cup frozen corn",
      "1 cup shredded cheddar",
      "0.5 cup jarred chicken gravy (or homemade)",
      "2 tbsp neutral oil",
      "1 tsp garlic powder",
      "1 tsp smoked paprika",
      "Salt, pepper",
    ],
    steps: [
      "Boil potatoes in salted water until fork-tender, 15 min. Drain. Mash with butter, warm cream, salt, and pepper until smooth.",
      "Season diced chicken with garlic powder, paprika, salt, and pepper. Heat oil in a skillet over medium-high. Cook chicken 6–8 min until browned and cooked through.",
      "Warm corn in the same skillet or microwave. Warm gravy on the stovetop.",
      "Build bowls: mashed potatoes → chicken → corn → gravy → shredded cheddar on top.",
    ],
    notes: "Jarred gravy works great here. Make the mashed potatoes rich with plenty of butter.",
  },
  {
    id: "bbq-chicken-thighs",
    title: "BBQ Chicken Thighs with Velveeta Mac and Sautéed Green Beans",
    category: "Dinner",
    description: "Saucy BBQ chicken thighs — Instant Pot or grill — with stovetop Velveeta mac and blistered green beans.",
    servings: 4,
    preptime: "10 min",
    cooktime: "35 min",
    tags: ["Chicken", "Comfort Food", "American"],
    ingredients: [
      "4 bone-in skin-on chicken thighs",
      "0.75 cup BBQ sauce",
      "8 oz elbow macaroni",
      "8 oz Velveeta, cubed",
      "0.5 cup milk",
      "1 lb green beans, trimmed",
      "3 cloves garlic, minced",
      "2 tbsp butter",
      "1 tbsp olive oil",
      "Salt, pepper, red pepper flakes",
    ],
    steps: [
      "Instant Pot: season chicken, pour ¼ cup BBQ sauce in pot. Pressure cook High 12 min, natural release 5 min. Broil on a sheet pan with remaining sauce 3–4 min until caramelized. Grill: season and grill over medium 6–7 min per side, brushing with sauce last 2 min.",
      "Cook macaroni per package. Drain. Return to pot over low heat. Add Velveeta and milk. Stir until melted and creamy. Season with pepper.",
      "Sauté green beans in olive oil over medium-high 4–5 min until blistered and tender-crisp. Add garlic 30 seconds. Finish with butter, salt, and red pepper flakes.",
      "Plate chicken with mac and green beans.",
    ],
    notes: "Instant Pot gives fall-off-the-bone chicken; grill gives better bark. Both work great.",
  },
  {
    id: "coconut-lime-chicken",
    title: "Coconut Lime Chicken over White Rice",
    category: "Dinner",
    description: "Seared chicken thighs simmered in a bright coconut milk, lime, and ginger sauce served over jasmine rice.",
    servings: 4,
    preptime: "5 min",
    cooktime: "30 min",
    tags: ["Chicken", "Caribbean"],
    ingredients: [
      "1.5 lbs boneless skinless chicken thighs",
      "1 can full-fat coconut milk (13.5 oz)",
      "1.5 cups jasmine rice, uncooked",
      "3 cups water",
      "2 limes, zested and juiced",
      "4 cloves garlic, minced",
      "1 tbsp fresh ginger, grated (or ½ tsp ground)",
      "2 tbsp fish sauce (or soy sauce)",
      "1 tbsp brown sugar or honey",
      "1 tbsp neutral oil",
      "Fresh cilantro and lime wedges for serving",
    ],
    steps: [
      "Cook jasmine rice in water with a pinch of salt. Set aside.",
      "Season chicken with salt and pepper. Heat oil over medium-high in a large skillet. Sear chicken 4–5 min per side until golden. Remove.",
      "Sauté garlic and ginger 1 min. Add coconut milk, lime zest, lime juice, fish sauce, and brown sugar. Stir and bring to a simmer.",
      "Return chicken to skillet. Simmer 10–12 min until cooked through and sauce slightly thickened.",
      "Taste and adjust: more lime for brightness, more fish sauce for umami.",
      "Serve over rice topped with cilantro and lime wedges.",
    ],
    notes: "Full-fat coconut milk only — light won't give the right body. Sauce reheats beautifully.",
  },
  {
    id: "beef-broccoli",
    title: "Beef & Broccoli over White Rice",
    category: "Dinner",
    description: "Velveted flank steak and broccoli in a glossy soy-oyster sauce stir-fry over jasmine rice.",
    servings: 4,
    preptime: "15 min",
    cooktime: "15 min",
    tags: ["Beef", "Asian"],
    ingredients: [
      "1.5 lbs flank steak or sirloin, thinly sliced against the grain",
      "1 head broccoli, cut into florets",
      "1.5 cups jasmine rice, uncooked",
      "0.25 cup soy sauce",
      "2 tbsp oyster sauce",
      "1 tbsp hoisin sauce",
      "1 tbsp brown sugar",
      "1 tbsp cornstarch",
      "2 tsp sesame oil",
      "4 cloves garlic, minced",
      "1 tsp fresh ginger, grated",
      "2 tbsp neutral oil",
      "Velveting: 1 tbsp soy sauce + 1 tbsp cornstarch + 1 tsp baking soda (fast) OR egg white + 1 tbsp cornstarch + 1 tbsp soy sauce (traditional)",
    ],
    steps: [
      "Velvet the beef: toss sliced beef in velveting marinade. Let sit 15–30 min (baking soda) or 30 min (egg white). Rinse baking soda method beef before cooking.",
      "Cook jasmine rice. Set aside.",
      "Blanch broccoli in salted boiling water 2 min, drain. Or stir-fry in oil 3–4 min.",
      "Mix sauce: soy sauce, oyster sauce, hoisin, brown sugar, cornstarch, and sesame oil.",
      "Heat wok or heavy skillet over very high heat. Add oil. Sear beef in batches — do not crowd — 1–2 min until browned. Remove.",
      "Add garlic and ginger 30 seconds. Add broccoli. Pour in sauce. Return beef. Toss everything 1 min until sauce is glossy and thickened. Serve over rice.",
    ],
    notes: "Baking soda velveting is faster (15 min, requires rinsing). Egg white is more traditional (30 min, better texture). High heat is non-negotiable.",
  },
  {
    id: "taco-salad",
    title: "Taco Salad with Valentina and Ranch Doritos",
    category: "Dinner",
    description: "Loaded taco salad bowl with seasoned ground beef, black beans, cheese, guac, Valentina, and crushed Ranch Doritos.",
    servings: 4,
    preptime: "10 min",
    cooktime: "15 min",
    tags: ["Mexican", "Beef"],
    ingredients: [
      "1 lb ground beef (80/20)",
      "2 tbsp taco seasoning",
      "1 head romaine lettuce, chopped",
      "1 can black beans, drained and rinsed (15 oz)",
      "1 cup cherry tomatoes, halved",
      "1 cup shredded Mexican cheese blend",
      "0.5 cup sour cream",
      "0.5 cup guacamole or sliced avocado",
      "Valentina hot sauce, to taste — essential",
      "1 bag Ranch Doritos, crushed",
      "Optional: salsa, jalapeño, cilantro",
    ],
    steps: [
      "Brown ground beef in a skillet over medium-high. Drain fat. Add taco seasoning and a splash of water. Cook 2 min until saucy.",
      "Build bowls: romaine as the base, then warm beef, black beans, tomatoes, cheese, guacamole, and sour cream.",
      "Hit with Valentina hot sauce.",
      "Crush Ranch Doritos and scatter on top right before serving so they stay crunchy.",
    ],
    notes: "Doritos go on last — they go soggy fast. Valentina is essential, not optional.",
  },

  // ── NEW RECIPES ──────────────────────────────────────────────────────────────

  {
    id: "fish-tacos",
    title: "Fish Tacos with Chipotle Crema",
    category: "Dinner",
    description: "Crispy seasoned halibut in corn tortillas with a smoky chipotle crema, quick cabbage slaw, and avocado.",
    servings: 4,
    preptime: "15 min",
    cooktime: "15 min",
    tags: ["Mexican", "Seafood"],
    ingredients: [
      "1.5 lbs halibut or cod fillets, cut into strips",
      "8 corn tortillas",
      "1 tsp chili powder",
      "1 tsp cumin",
      "1 tsp garlic powder",
      "0.5 tsp smoked paprika",
      "2 tbsp neutral oil",
      "— Chipotle Crema —",
      "0.5 cup sour cream",
      "1 tbsp chipotle in adobo, minced (plus sauce from can)",
      "1 lime, juiced",
      "1 clove garlic, grated",
      "— Quick Slaw —",
      "2 cups green cabbage, finely shredded",
      "2 tbsp apple cider vinegar",
      "1 tbsp olive oil",
      "1 tsp honey",
      "— Toppings —",
      "1 avocado, sliced",
      "0.5 cup fresh cilantro",
      "Lime wedges, Valentina or hot sauce",
    ],
    steps: [
      "Make chipotle crema: combine sour cream, minced chipotle with adobo sauce, lime juice, and grated garlic. Stir well. Refrigerate until ready to serve.",
      "Make quick slaw: toss shredded cabbage with apple cider vinegar, olive oil, honey, and a pinch of salt. Let sit while you cook the fish.",
      "Season fish strips with chili powder, cumin, garlic powder, smoked paprika, salt, and pepper.",
      "Heat oil in a skillet over medium-high. Cook fish in batches 2–3 min per side until flaky and golden. Don't crowd the pan.",
      "Warm corn tortillas directly over a gas flame or in a dry skillet.",
      "Build tacos: tortilla → slaw → fish → chipotle crema → avocado → cilantro → squeeze of lime. Add hot sauce.",
    ],
    notes: "Halibut preferred. Fish cooks fast — don't overcook. Crema can be made 2 days ahead. Slaw is best fresh.",
  },
  {
    id: "falafel-pita",
    title: "Falafel Pita with Tzatziki and Green Goddess",
    category: "Dinner",
    description: "Crispy herb-packed falafel in warm pita with cool tzatziki, fresh vegetables, and green goddess dressing.",
    servings: 4,
    preptime: "20 min",
    cooktime: "20 min",
    tags: ["Vegetarian", "Mediterranean"],
    ingredients: [
      "— Falafel —",
      "2 cans chickpeas, drained and very dry (15 oz each)",
      "0.5 cup fresh parsley",
      "0.5 cup fresh cilantro",
      "4 cloves garlic",
      "1 small onion, roughly chopped",
      "1 tsp cumin",
      "1 tsp coriander",
      "0.5 tsp cayenne",
      "3 tbsp all-purpose flour",
      "1 tsp baking powder",
      "3 tbsp neutral oil for frying",
      "— Tzatziki —",
      "1 cup plain Greek yogurt",
      "0.5 English cucumber, grated and squeezed dry",
      "2 cloves garlic, grated",
      "1 tbsp fresh dill",
      "1 tbsp lemon juice",
      "— Assembly —",
      "4 pita breads",
      "1 cup cherry tomatoes, halved",
      "0.5 English cucumber, diced",
      "0.5 red onion, thinly sliced",
      "Green goddess dressing, store-bought or homemade",
    ],
    steps: [
      "Make tzatziki: combine Greek yogurt, grated cucumber (squeezed dry), garlic, dill, and lemon juice. Season with salt. Refrigerate.",
      "Make falafel: pulse chickpeas, parsley, cilantro, onion, garlic, cumin, coriander, and cayenne in a food processor until a coarse paste forms — not smooth. Transfer to a bowl. Stir in flour, baking powder, and 1 tsp salt. Mixture should hold when pressed.",
      "Form into small patties or balls, about 2 tbsp each.",
      "Heat oil in a skillet over medium-high. Fry falafel in batches 3–4 min per side until deeply golden and crispy. Don't flip too early.",
      "Warm pitas briefly in the oven or over a flame.",
      "Assemble: open pita, spread tzatziki, add 3–4 falafel, top with tomato, cucumber, red onion, and a drizzle of green goddess.",
    ],
    notes: "Do not over-process the chickpeas — coarse texture is key. Chickpeas must be completely dry. Falafel mixture can be made a day ahead. Tzatziki holds 3 days.",
  },
  {
    id: "tuna-avocado-toast",
    title: "Tuna Avocado Toast",
    category: "Dinner",
    description: "Elevated tuna salad on crushed avocado toast with capers, Dijon, everything bagel seasoning, and red pepper flakes.",
    servings: 2,
    preptime: "15 min",
    cooktime: "0 min",
    tags: ["Seafood", "Mexican"],
    ingredients: [
      "2 cans solid white albacore tuna in water, drained (5 oz each)",
      "2 ripe avocados",
      "4 slices thick sourdough or multigrain bread, toasted",
      "2 tbsp mayonnaise",
      "1 tbsp Dijon mustard",
      "1 tbsp capers, roughly chopped",
      "1 lemon, juiced",
      "0.25 cup red onion, finely diced",
      "1 tsp everything bagel seasoning",
      "Red pepper flakes, salt, pepper",
      "Optional: sliced radish, arugula, cucumber",
    ],
    steps: [
      "Mix tuna with mayo, Dijon, capers, half the lemon juice, and red onion. Season with salt and pepper. Taste and adjust.",
      "Halve and pit avocados. Scoop flesh into a bowl. Add remaining lemon juice and a pinch of salt. Mash to desired texture — leave some chunks.",
      "Toast bread until deeply golden.",
      "Spread avocado on toast. Top with tuna mixture. Sprinkle with everything bagel seasoning and red pepper flakes.",
      "Add optional toppings. Serve immediately.",
    ],
    notes: "Eat promptly — toasted bread softens quickly. Tuna mixture can be made ahead and refrigerated up to 2 days.",
  },
  {
    id: "chicken-pot-pie-casserole",
    title: "Chicken Pot Pie Casserole",
    category: "Dinner",
    description: "Classic pot pie filling with chicken, vegetables, and creamy sauce topped with golden biscuits baked until bubbling.",
    servings: 6,
    preptime: "15 min",
    cooktime: "40 min",
    tags: ["Chicken", "Comfort Food"],
    ingredients: [
      "2 lbs boneless skinless chicken thighs — or rotisserie chicken, shredded",
      "1 cup frozen peas",
      "1 cup frozen corn",
      "2 medium carrots, diced",
      "2 stalks celery, diced",
      "1 medium yellow onion, diced",
      "3 cloves garlic, minced",
      "3 tbsp butter",
      "3 tbsp all-purpose flour",
      "2 cups chicken stock (Better Than Bouillon)",
      "0.75 cup whole milk or cream",
      "1 tsp dried thyme",
      "1 tsp dried rosemary",
      "1 tube refrigerated biscuit dough (8-count) or 1 sheet puff pastry",
      "1 egg, beaten for egg wash",
      "Salt, pepper",
    ],
    steps: [
      "Preheat oven to 400°F. If using raw chicken, poach or bake at 400°F for 20 min until cooked through. Shred and set aside.",
      "In a large oven-safe skillet or Dutch oven, melt butter over medium. Sauté onion, carrot, and celery 5–6 min until softened. Add garlic 30 seconds.",
      "Sprinkle flour over vegetables. Stir 1–2 min. Slowly pour in chicken stock and milk, stirring constantly. Bring to a simmer until thickened, 3–4 min.",
      "Add thyme, rosemary, peas, corn, and shredded chicken. Season generously with salt and pepper. Taste and adjust.",
      "Remove from heat. Top filling with biscuit rounds (slightly overlapping) or puff pastry. Brush with egg wash.",
      "Bake 22–25 min until topping is deep golden brown and filling is bubbling at the edges. Rest 5 min before serving.",
    ],
    notes: "Make-ahead: prepare filling up to 2 days ahead, refrigerate. Add biscuit topping just before baking. Rotisserie chicken is the weeknight shortcut. Freezes well without the biscuit topping.",
  },
  {
    id: "homemade-pita",
    title: "Homemade Pita Bread",
    category: "Soups, Sides & Appetizers",
    description: "Soft, puffy homemade pita cooked in a cast iron skillet — essential for falafel and hummus.",
    servings: 8,
    preptime: "15 min",
    cooktime: "15 min (plus 1 hr rise)",
    tags: ["Bread"],
    ingredients: [
      "3 cups all-purpose flour, plus more for dusting",
      "1 packet instant yeast (2¼ tsp)",
      "1 cup warm water (110°F)",
      "1 tsp sugar",
      "1.5 tsp salt",
      "2 tbsp olive oil",
    ],
    steps: [
      "Combine warm water, sugar, and yeast. Let sit 5 min until foamy.",
      "In a large bowl, mix flour and salt. Add yeast mixture and olive oil. Stir until dough comes together.",
      "Knead on a floured surface 8–10 min until smooth and elastic. Or use a stand mixer with dough hook on medium 6–7 min.",
      "Place dough in an oiled bowl, cover with a damp towel. Let rise 1 hour until doubled.",
      "Punch down. Divide into 8 equal portions. Roll each into a smooth ball, then roll flat to about ⅛ inch thick and roughly 6 inches across.",
      "Heat a dry cast iron skillet or heavy pan over high heat until very hot. Cook each pita 1–2 min per side until it puffs and gets golden spots. Wrap in a clean towel immediately to keep soft.",
    ],
    notes: "The pocket forms when the pita puffs from steam. Stack and wrap in a towel right off the pan. Freeze extras and reheat wrapped in damp paper towels in microwave 30 seconds.",
  },
  {
    id: "instant-pot-cheddar-grits",
    title: "Instant Pot Cheddar Grits",
    category: "Soups, Sides & Appetizers",
    description: "Creamy stone-ground grits cooked under pressure with chicken stock, sharp cheddar, and butter.",
    servings: 4,
    preptime: "5 min",
    cooktime: "20 min",
    tags: ["Comfort Food"],
    ingredients: [
      "1 cup stone-ground grits (not instant)",
      "3 cups water",
      "1 cup chicken stock (Better Than Bouillon)",
      "1.5 cups shredded sharp cheddar",
      "3 tbsp butter",
      "0.5 cup whole milk or cream, added after cooking",
      "1 tsp salt",
      "0.5 tsp white pepper or black pepper",
      "Optional: pinch of cayenne, hot sauce",
    ],
    steps: [
      "Add grits, water, stock, and salt to the Instant Pot. Stir to combine.",
      "Lock lid, valve to sealing. Cook on High Pressure 10 minutes.",
      "Natural release 10 min, then carefully quick release remaining pressure.",
      "Open lid and stir — grits will look thin at first but thicken quickly.",
      "Add butter and shredded cheddar. Stir until fully melted and incorporated.",
      "Stir in milk or cream to reach desired consistency. Season with pepper and cayenne. Serve immediately.",
    ],
    notes: "Grits thicken significantly as they cool — serve promptly or reheat with a splash of water or milk. Stone-ground only — instant grits turn to mush under pressure.",
  },
];
