export const RECIPE_CATEGORIES = [
  "All",
  "Weeknight",
  "Chicken",
  "Seafood",
  "Mexican",
  "Comfort Food",
  "Lighter Fare",
  "Soup",
  "Vegetarian",
  "Make-Ahead",
  "30 min",
  "Side",
  "Bread",
  "Quick",
];

export const CORE_RECIPES = [
  {
    id: "taco-rice-skillet",
    title: "Taco Rice Skillet",
    tags: ["Weeknight", "Mexican", "30 min"],
    time: 30,
    servings: 4,
    ingredients: [
      { amount: 1, unit: "lb", item: "ground beef (80/20)" },
      { amount: 1, unit: "cup", item: "long grain white rice, uncooked" },
      { amount: 2, unit: "cups", item: "chicken stock (Better Than Bouillon)" },
      { amount: 1, unit: "can", item: "diced tomatoes with green chiles (10 oz)" },
      { amount: 1, unit: "can", item: "black beans, drained and rinsed (15 oz)" },
      { amount: 1, unit: "cup", item: "corn kernels, frozen or canned" },
      { amount: 2, unit: "tbsp", item: "taco seasoning (or 1 packet)" },
      { amount: 1, unit: "cup", item: "shredded Mexican cheese blend" },
      { amount: 2, unit: "tbsp", item: "neutral oil" },
      { amount: "", unit: "", item: "Salt and pepper to taste" },
      { amount: "", unit: "", item: "Optional: sour cream, avocado, jalapeño, cilantro" },
    ],
    steps: [
      "Heat oil in a large skillet over medium-high. Add ground beef, break apart, and cook until browned, 5–6 min. Drain excess fat.",
      "Add taco seasoning and stir to coat. Toast 30 seconds.",
      "Add uncooked rice and stir to combine with the beef.",
      "Pour in chicken stock and diced tomatoes. Stir, bring to a boil, then reduce heat to low. Cover and cook 18 min until rice is tender and liquid absorbed.",
      "Stir in black beans and corn. Heat through 2 min.",
      "Top with cheese, cover off heat 1–2 min to melt. Serve from the skillet with desired toppings.",
    ],
    notes: "Make-ahead: Cook full skillet, refrigerate up to 4 days. Reheat in skillet with a splash of water. Freezes well up to 3 months.",
  },
  {
    id: "lemon-orzo-chicken",
    title: "Lemon Orzo with Roasted Chicken Thighs",
    tags: ["Weeknight", "Chicken"],
    time: 45,
    servings: 4,
    ingredients: [
      { amount: 4, unit: "", item: "bone-in skin-on chicken thighs" },
      { amount: 1.5, unit: "cups", item: "orzo" },
      { amount: 3, unit: "cups", item: "chicken stock (Better Than Bouillon)" },
      { amount: 1, unit: "", item: "lemon, zested and juiced" },
      { amount: 4, unit: "cloves", item: "garlic, minced" },
      { amount: 1, unit: "cup", item: "baby spinach" },
      { amount: 0.5, unit: "cup", item: "grated Parmesan" },
      { amount: 2, unit: "tbsp", item: "butter" },
      { amount: 2, unit: "tbsp", item: "olive oil" },
      { amount: 1, unit: "tsp", item: "Italian seasoning" },
      { amount: "", unit: "", item: "Salt and pepper to taste" },
    ],
    steps: [
      "Preheat oven to 425°F. Pat chicken dry, season generously with salt, pepper, and Italian seasoning.",
      "Heat olive oil in an oven-safe skillet over medium-high. Sear chicken thighs skin-side down 5–6 min until golden. Flip and sear 2 min more. Transfer to a plate.",
      "In the same skillet, sauté garlic 30 seconds. Add orzo and toast 1–2 min, stirring.",
      "Add stock, lemon zest, and lemon juice. Bring to a simmer. Nestle chicken thighs back in skin-side up.",
      "Transfer skillet to oven. Roast 20–22 min until chicken is cooked through (165°F) and orzo has absorbed most of the liquid.",
      "Remove from oven. Stir in spinach and butter. Top with Parmesan. Rest 5 min before serving.",
    ],
    notes: "One-pan meal. Batch prep: sear chicken on the weekend and refrigerate; finish in oven on weeknight.",
  },
  {
    id: "beef-stroganoff",
    title: "Ground Beef Stroganoff",
    tags: ["Weeknight", "Comfort Food", "30 min"],
    time: 30,
    servings: 4,
    ingredients: [
      { amount: 1, unit: "lb", item: "ground beef (80/20)" },
      { amount: 8, unit: "oz", item: "egg noodles" },
      { amount: 8, unit: "oz", item: "cremini mushrooms, sliced" },
      { amount: 1, unit: "", item: "medium yellow onion, diced" },
      { amount: 3, unit: "cloves", item: "garlic, minced" },
      { amount: 1, unit: "cup", item: "sour cream" },
      { amount: 1, unit: "cup", item: "beef stock (Better Than Bouillon)" },
      { amount: 2, unit: "tbsp", item: "Worcestershire sauce" },
      { amount: 1, unit: "tbsp", item: "Dijon mustard" },
      { amount: 2, unit: "tbsp", item: "all-purpose flour" },
      { amount: 2, unit: "tbsp", item: "butter" },
      { amount: 1, unit: "tbsp", item: "neutral oil" },
      { amount: "", unit: "", item: "Salt, pepper, fresh parsley for garnish" },
    ],
    steps: [
      "Cook egg noodles according to package. Reserve ½ cup pasta water. Drain and set aside.",
      "Heat oil in a large skillet over medium-high. Brown beef, breaking apart, 5–6 min. Season with salt and pepper. Remove to a bowl.",
      "In the same skillet, add butter. Sauté onion 3 min. Add mushrooms and cook until deeply browned, 5–6 min. Add garlic 30 seconds.",
      "Sprinkle flour over vegetables, stir 1 min. Add beef stock and Worcestershire. Bring to a simmer, stirring until thickened, 3 min.",
      "Reduce heat to low. Stir in sour cream and Dijon — do not boil. Return beef to skillet.",
      "Add noodles and toss to combine. Add pasta water to loosen if needed. Season to taste. Garnish with parsley.",
    ],
    notes: "Mushrooms must be deeply browned — don't rush this step. Sour cream will break if boiled.",
  },
  {
    id: "halibut-cilantro-rice",
    title: "Pan-Seared Halibut with Cilantro Lime Rice and Roasted Broccoli",
    tags: ["Weeknight", "Seafood"],
    time: 40,
    servings: 4,
    ingredients: [
      { amount: 1.5, unit: "lbs", item: "halibut fillets" },
      { amount: 1.5, unit: "cups", item: "jasmine rice, uncooked" },
      { amount: 3, unit: "cups", item: "water" },
      { amount: 1, unit: "head", item: "broccoli, cut into florets" },
      { amount: 1, unit: "", item: "lime, zested and juiced" },
      { amount: 0.5, unit: "cup", item: "fresh cilantro, chopped" },
      { amount: 3, unit: "tbsp", item: "olive oil, divided" },
      { amount: 2, unit: "tbsp", item: "butter" },
      { amount: 3, unit: "cloves", item: "garlic, minced" },
      { amount: "", unit: "", item: "Salt, pepper, red pepper flakes" },
    ],
    steps: [
      "Preheat oven to 425°F. Toss broccoli with 1 tbsp olive oil, salt, and pepper. Roast 20–22 min until crispy edged.",
      "Cook jasmine rice in water with a pinch of salt. When done, fluff with fork and stir in lime zest, lime juice, cilantro, and 1 tbsp olive oil. Season to taste.",
      "Pat fish dry. Season generously with salt and pepper.",
      "Heat remaining olive oil in a stainless skillet over medium-high until shimmering. Add fish presentation-side down. Do not move. Sear 3–4 min until a golden crust forms.",
      "Flip fish. Add butter and garlic. Baste 1–2 min until fish is just cooked through.",
      "Plate rice, top with fish, serve broccoli alongside. Finish with a squeeze of lime.",
    ],
    notes: "Let the fish release naturally — if it sticks, it's not ready to flip. Halibut preferred over salmon.",
  },
  {
    id: "gazpacho",
    title: "Gazpacho",
    tags: ["Lighter Fare", "Soup", "Make-Ahead", "Vegetarian"],
    time: 20,
    servings: 6,
    ingredients: [
      { amount: 2, unit: "lbs", item: "ripe Roma tomatoes, cored and roughly chopped" },
      { amount: 1, unit: "", item: "English cucumber, roughly chopped" },
      { amount: 1, unit: "", item: "red bell pepper, seeded and roughly chopped" },
      { amount: 0.5, unit: "", item: "small red onion, roughly chopped" },
      { amount: 2, unit: "cloves", item: "garlic" },
      { amount: 3, unit: "tbsp", item: "sherry vinegar (or red wine vinegar)" },
      { amount: 0.25, unit: "cup", item: "extra virgin olive oil" },
      { amount: 1, unit: "tsp", item: "salt" },
      { amount: 0.5, unit: "tsp", item: "cumin" },
      { amount: "", unit: "", item: "Optional garnish: diced cucumber, croutons, drizzle of olive oil" },
    ],
    steps: [
      "Combine tomatoes, cucumber, bell pepper, red onion, and garlic in a blender or food processor. Blend until smooth.",
      "Add vinegar, olive oil, salt, and cumin. Blend again.",
      "Taste and adjust — more vinegar for brightness, more salt as needed.",
      "Refrigerate at least 2 hours (overnight is best). Serve cold with desired garnishes.",
    ],
    notes: "Best made 24 hours ahead. Keeps refrigerated up to 5 days. Tomato quality is everything — do not make in winter.",
  },
  {
    id: "pomodoro-crudo",
    title: "Pasta al Pomodoro Crudo",
    tags: ["Weeknight", "Lighter Fare", "Vegetarian", "30 min"],
    time: 25,
    servings: 4,
    ingredients: [
      { amount: 1, unit: "lb", item: "spaghetti or linguine" },
      { amount: 2, unit: "lbs", item: "ripe tomatoes, diced (or halved cherry tomatoes)" },
      { amount: 4, unit: "cloves", item: "garlic, thinly sliced" },
      { amount: 0.5, unit: "cup", item: "fresh basil leaves, torn" },
      { amount: 0.25, unit: "cup", item: "extra virgin olive oil" },
      { amount: 0.5, unit: "tsp", item: "red pepper flakes" },
      { amount: "", unit: "", item: "Salt to taste" },
      { amount: "", unit: "", item: "Pecorino Romano or Parmesan to finish" },
    ],
    steps: [
      "Combine diced tomatoes, garlic, basil, olive oil, red pepper flakes, and 1 tsp salt in a large bowl. Let sit at room temperature 30 min to 1 hour.",
      "Cook pasta in heavily salted boiling water until al dente. Reserve 1 cup pasta water before draining.",
      "Drain pasta and immediately add to the bowl of raw tomatoes. Toss vigorously, adding pasta water a splash at a time until a loose sauce forms.",
      "Season to taste. Serve immediately topped with grated cheese.",
    ],
    notes: "Raw sauce — the heat of the pasta lightly warms the tomatoes. Do not make in winter. Tomato quality is everything.",
  },
  {
    id: "tuscan-chicken-casserole",
    title: "Lighter Tuscan Chicken Casserole",
    tags: ["Weeknight", "Chicken", "Make-Ahead"],
    time: 50,
    servings: 5,
    ingredients: [
      { amount: 2, unit: "lbs", item: "boneless skinless chicken thighs" },
      { amount: 1, unit: "lb", item: "baby potatoes, halved" },
      { amount: 2, unit: "cups", item: "broccoli florets" },
      { amount: 1, unit: "cup", item: "sun-dried tomatoes in oil, drained and chopped" },
      { amount: 4, unit: "cloves", item: "garlic, minced" },
      { amount: 1, unit: "cup", item: "chicken stock (Better Than Bouillon)" },
      { amount: 0.5, unit: "cup", item: "plain Greek yogurt or light cream" },
      { amount: 2, unit: "tbsp", item: "olive oil" },
      { amount: 1, unit: "tsp", item: "Italian seasoning" },
      { amount: 1, unit: "tsp", item: "smoked paprika" },
      { amount: "", unit: "", item: "Salt, pepper, fresh parsley" },
    ],
    steps: [
      "Preheat oven to 400°F. Season chicken thighs with Italian seasoning, smoked paprika, salt, and pepper.",
      "Heat olive oil in an oven-safe Dutch oven over medium-high. Sear chicken 3–4 min per side until golden. Remove.",
      "Sauté garlic 30 seconds. Add sun-dried tomatoes and potatoes. Pour in chicken stock.",
      "Return chicken to pan. Cover and transfer to oven. Bake 25 min.",
      "Remove from oven. Add broccoli around the chicken. Bake uncovered 10 more min.",
      "Remove chicken. Stir Greek yogurt into the pan sauce. Return chicken. Garnish with parsley and serve.",
    ],
    notes: "Batch prep: sear chicken on weekend, store separately. Assemble and bake on weeknight. Freezes well before adding yogurt.",
  },
  {
    id: "chicken-marsala",
    title: "Chicken Marsala with Cream Cheese Mashed Potatoes",
    tags: ["Weeknight", "Chicken", "Comfort Food"],
    time: 45,
    servings: 4,
    ingredients: [
      { amount: 4, unit: "", item: "boneless skinless chicken breasts, pounded thin" },
      { amount: 8, unit: "oz", item: "cremini mushrooms, sliced" },
      { amount: 0.75, unit: "cup", item: "Marsala wine (dry) — Madeira also excellent" },
      { amount: 0.5, unit: "cup", item: "chicken stock (Better Than Bouillon)" },
      { amount: 2, unit: "tbsp", item: "all-purpose flour" },
      { amount: 3, unit: "tbsp", item: "butter, divided" },
      { amount: 2, unit: "tbsp", item: "olive oil" },
      { amount: 2, unit: "cloves", item: "garlic, minced" },
      { amount: 2, unit: "lbs", item: "Yukon Gold potatoes, cubed" },
      { amount: 4, unit: "oz", item: "cream cheese, softened" },
      { amount: 0.5, unit: "cup", item: "warm milk or cream" },
      { amount: "", unit: "", item: "Salt, pepper, fresh parsley" },
    ],
    steps: [
      "Boil potatoes in salted water until fork-tender, 15–18 min. Drain. Mash with cream cheese, warm milk, salt, and pepper until smooth. Keep warm.",
      "Season chicken with salt and pepper, dredge lightly in flour.",
      "Heat oil and 1 tbsp butter in a large skillet over medium-high. Sear chicken 4–5 min per side until golden. Remove.",
      "In same skillet, add mushrooms. Cook until deeply browned, 5–6 min. Add garlic 30 seconds.",
      "Deglaze with Marsala, scraping up the fond. Add chicken stock. Simmer 3–4 min until slightly reduced.",
      "Swirl in remaining 2 tbsp butter. Return chicken to pan and coat with sauce. Serve over mashed potatoes, garnished with parsley.",
    ],
    notes: "Mushrooms must be deeply browned before deglazing. Madeira is an excellent Marsala substitute.",
  },
  {
    id: "halibut-white-bean",
    title: "Pan-Seared Halibut over White Bean Puree with Broccolini",
    tags: ["Weeknight", "Seafood"],
    time: 35,
    servings: 4,
    ingredients: [
      { amount: 1.5, unit: "lbs", item: "halibut fillets" },
      { amount: 2, unit: "cans", item: "white cannellini beans, drained and rinsed (15 oz each)" },
      { amount: 1, unit: "bunch", item: "broccolini, trimmed" },
      { amount: 4, unit: "cloves", item: "garlic, divided" },
      { amount: 0.5, unit: "cup", item: "chicken stock (Better Than Bouillon)" },
      { amount: 3, unit: "tbsp", item: "olive oil, divided" },
      { amount: 2, unit: "tbsp", item: "butter" },
      { amount: 1, unit: "", item: "lemon, for juice and zest" },
      { amount: 1, unit: "tsp", item: "fresh thyme or rosemary" },
      { amount: "", unit: "", item: "Red pepper flakes, salt, pepper" },
    ],
    steps: [
      "Make white bean puree: heat 1 tbsp olive oil over medium. Sauté 2 cloves garlic 1 min. Add beans and stock. Simmer 5 min. Blend or mash until smooth. Season with salt, pepper, and lemon zest. Keep warm.",
      "Sauté broccolini in a hot skillet with 1 tbsp olive oil until bright green and tender-crisp, 3–4 min. Season and set aside.",
      "Pat halibut dry. Season generously with salt and pepper.",
      "Heat remaining olive oil in a stainless skillet over medium-high until shimmering. Sear halibut presentation-side down 3–4 min without moving.",
      "Flip. Add butter, remaining garlic, and thyme. Baste 1–2 min until just cooked through.",
      "Spoon white bean puree onto plates, top with halibut. Arrange broccolini alongside. Finish with lemon juice and red pepper flakes.",
    ],
    notes: "Don't move the fish until it releases naturally. Bean puree can be made 2 days ahead.",
  },
  {
    id: "scallops-grits",
    title: "Seared Scallops with Cheddar Grits and Wilted Spinach",
    tags: ["Weeknight", "Seafood"],
    time: 35,
    servings: 4,
    ingredients: [
      { amount: 1.5, unit: "lbs", item: "large sea scallops (dry-packed)" },
      { amount: 1, unit: "cup", item: "stone-ground grits (not instant)" },
      { amount: 4, unit: "cups", item: "chicken stock (Better Than Bouillon)" },
      { amount: 1, unit: "cup", item: "shredded sharp cheddar" },
      { amount: 2, unit: "tbsp", item: "butter, divided" },
      { amount: 4, unit: "cups", item: "baby spinach" },
      { amount: 3, unit: "cloves", item: "garlic, minced" },
      { amount: 2, unit: "tbsp", item: "neutral oil (high smoke point)" },
      { amount: 0.25, unit: "cup", item: "dry white wine or chicken stock" },
      { amount: "", unit: "", item: "Salt, pepper, lemon wedges for serving" },
    ],
    steps: [
      "Bring stock to a boil. Whisk in grits with a pinch of salt. Reduce heat to low. Cook 20–25 min stirring frequently until thick and creamy. Stir in cheddar and 1 tbsp butter. Season and keep warm.",
      "Pat scallops very dry with paper towels. Remove side muscle. Season with salt and pepper.",
      "Heat neutral oil in a stainless skillet over high until just smoking. Add scallops with space between them. Do not move. Sear 2 min until a deep golden crust forms.",
      "Flip scallops. Add 1 tbsp butter and baste 1–2 min. Just translucent in center. Remove to a plate.",
      "In same skillet, sauté garlic 30 seconds. Add spinach and wine. Toss until wilted, 1–2 min. Season.",
      "Spoon grits into bowls. Top with spinach and scallops. Serve with lemon wedges.",
    ],
    notes: "Dry-packed scallops only — wet-packed won't sear. Scallops must be bone dry. Do not crowd the pan.",
  },
  {
    id: "smash-burgers",
    title: "Smash Burgers",
    tags: ["Weeknight", "Comfort Food", "30 min"],
    time: 25,
    servings: 4,
    ingredients: [
      { amount: 1.5, unit: "lbs", item: "ground beef (80/20)" },
      { amount: 4, unit: "", item: "potato buns" },
      { amount: 4, unit: "slices", item: "American cheese" },
      { amount: 0.5, unit: "cup", item: "mayonnaise" },
      { amount: 2, unit: "tbsp", item: "ketchup" },
      { amount: 1, unit: "tbsp", item: "yellow mustard" },
      { amount: 1, unit: "tbsp", item: "dill pickle brine" },
      { amount: 1, unit: "tsp", item: "smoked paprika" },
      { amount: 1, unit: "tsp", item: "garlic powder" },
      { amount: "", unit: "", item: "Toppings: dill pickles, shredded lettuce, sliced onion" },
      { amount: "", unit: "", item: "Butter for toasting buns" },
    ],
    steps: [
      "Mix smash sauce: mayo, ketchup, mustard, pickle brine, paprika, garlic powder. Refrigerate.",
      "Divide beef into 3 oz balls — about 6 total. Do not season yet.",
      "Heat a cast iron or heavy skillet over high for 3–4 min until very hot. Add a small pat of butter.",
      "Place beef balls in pan with space. Immediately smash flat with a spatula or burger press. Season tops with salt and pepper.",
      "Cook 2–3 min until edges are deeply browned and crispy. Flip once. Add cheese immediately. Cook 30 seconds more.",
      "Toast buns in a separate pan with butter. Assemble with sauce, pickles, lettuce, onion.",
    ],
    notes: "Smash immediately when beef hits the pan — it only smashes flat while the fat is still cold. Two thin patties per bun is the move.",
  },
  {
    id: "kfc-bowls",
    title: "KFC-Style Mashed Potato Bowls",
    tags: ["Weeknight", "Comfort Food", "30 min"],
    time: 35,
    servings: 4,
    ingredients: [
      { amount: 2, unit: "lbs", item: "Yukon Gold potatoes, peeled and cubed" },
      { amount: 1, unit: "lb", item: "boneless skinless chicken thighs, diced" },
      { amount: 3, unit: "tbsp", item: "butter" },
      { amount: 0.5, unit: "cup", item: "warm cream or milk" },
      { amount: 1, unit: "cup", item: "frozen corn" },
      { amount: 1, unit: "cup", item: "shredded cheddar" },
      { amount: 0.5, unit: "cup", item: "jarred chicken gravy (or homemade)" },
      { amount: 2, unit: "tbsp", item: "neutral oil" },
      { amount: 1, unit: "tsp", item: "garlic powder" },
      { amount: 1, unit: "tsp", item: "smoked paprika" },
      { amount: "", unit: "", item: "Salt, pepper" },
    ],
    steps: [
      "Boil potatoes in salted water until fork-tender, 15 min. Drain. Mash with butter, warm cream, salt, and pepper until smooth.",
      "Season diced chicken with garlic powder, paprika, salt, and pepper. Heat oil in a skillet over medium-high. Cook chicken 6–8 min until browned and cooked through.",
      "Warm corn in the same skillet or microwave. Warm gravy on the stovetop.",
      "Build bowls: mashed potatoes → chicken → corn → gravy → shredded cheddar on top.",
    ],
    notes: "Jarred gravy works great here. Make the mashed potatoes rich with plenty of butter.",
  },
  {
    id: "bbq-chicken-thighs",
    title: "BBQ Chicken Thighs with Velveeta Mac and Sautéed Green Beans",
    tags: ["Weeknight", "Chicken"],
    time: 45,
    servings: 4,
    ingredients: [
      { amount: 4, unit: "", item: "bone-in skin-on chicken thighs" },
      { amount: 0.75, unit: "cup", item: "BBQ sauce" },
      { amount: 8, unit: "oz", item: "elbow macaroni" },
      { amount: 8, unit: "oz", item: "Velveeta, cubed" },
      { amount: 0.5, unit: "cup", item: "milk" },
      { amount: 1, unit: "lb", item: "green beans, trimmed" },
      { amount: 3, unit: "cloves", item: "garlic, minced" },
      { amount: 2, unit: "tbsp", item: "butter" },
      { amount: 1, unit: "tbsp", item: "olive oil" },
      { amount: "", unit: "", item: "Salt, pepper, red pepper flakes" },
    ],
    steps: [
      "Instant Pot: Season chicken, pour ¼ cup BBQ sauce in pot. Pressure cook High 12 min, natural release 5 min. Broil on a sheet pan with remaining sauce 3–4 min until caramelized. Grill: Season and grill over medium 6–7 min per side, brushing with sauce last 2 min.",
      "Cook macaroni per package. Drain. Return to pot over low heat. Add Velveeta and milk. Stir until melted and creamy. Season with pepper.",
      "Sauté green beans in olive oil over medium-high 4–5 min until blistered and tender-crisp. Add garlic 30 seconds. Finish with butter, salt, and red pepper flakes.",
      "Plate chicken with mac and green beans.",
    ],
    notes: "Instant Pot gives fall-off-the-bone chicken; grill gives better bark. Both work great.",
  },
  {
    id: "coconut-lime-chicken",
    title: "Coconut Lime Chicken over White Rice",
    tags: ["Weeknight", "Chicken"],
    time: 35,
    servings: 4,
    ingredients: [
      { amount: 1.5, unit: "lbs", item: "boneless skinless chicken thighs" },
      { amount: 1, unit: "can", item: "full-fat coconut milk (13.5 oz)" },
      { amount: 1.5, unit: "cups", item: "jasmine rice, uncooked" },
      { amount: 3, unit: "cups", item: "water" },
      { amount: 2, unit: "", item: "limes, zested and juiced" },
      { amount: 4, unit: "cloves", item: "garlic, minced" },
      { amount: 1, unit: "tbsp", item: "fresh ginger, grated (or ½ tsp ground)" },
      { amount: 2, unit: "tbsp", item: "fish sauce (or soy sauce)" },
      { amount: 1, unit: "tbsp", item: "brown sugar or honey" },
      { amount: 1, unit: "tbsp", item: "neutral oil" },
      { amount: "", unit: "", item: "Fresh cilantro and lime wedges for serving" },
    ],
    steps: [
      "Cook jasmine rice in water with a pinch of salt. Set aside.",
      "Season chicken with salt and pepper. Heat oil over medium-high in a large skillet. Sear chicken 4–5 min per side until golden. Remove.",
      "Sauté garlic and ginger 1 min. Add coconut milk, lime zest, lime juice, fish sauce, and brown sugar. Stir and bring to a simmer.",
      "Return chicken to skillet. Simmer 10–12 min until cooked through and sauce slightly thickened.",
      "Taste and adjust: more lime for brightness, more fish sauce for umami.",
      "Serve over rice topped with cilantro and lime wedges.",
    ],
    notes: "Full-fat coconut milk only. Sauce reheats beautifully.",
  },
  {
    id: "beef-broccoli",
    title: "Beef & Broccoli over White Rice",
    tags: ["Weeknight", "30 min"],
    time: 30,
    servings: 4,
    ingredients: [
      { amount: 1.5, unit: "lbs", item: "flank steak or sirloin, thinly sliced against the grain" },
      { amount: 1, unit: "head", item: "broccoli, cut into florets" },
      { amount: 1.5, unit: "cups", item: "jasmine rice, uncooked" },
      { amount: 0.25, unit: "cup", item: "soy sauce" },
      { amount: 2, unit: "tbsp", item: "oyster sauce" },
      { amount: 1, unit: "tbsp", item: "hoisin sauce" },
      { amount: 1, unit: "tbsp", item: "brown sugar" },
      { amount: 1, unit: "tbsp", item: "cornstarch" },
      { amount: 2, unit: "tsp", item: "sesame oil" },
      { amount: 4, unit: "cloves", item: "garlic, minced" },
      { amount: 1, unit: "tsp", item: "fresh ginger, grated" },
      { amount: 2, unit: "tbsp", item: "neutral oil" },
      { amount: "", unit: "", item: "Velveting: 1 tbsp soy sauce + 1 tbsp cornstarch + 1 tsp baking soda (fast) OR egg white + 1 tbsp cornstarch + 1 tbsp soy sauce (traditional)" },
    ],
    steps: [
      "Velvet the beef: toss sliced beef in velveting marinade. Let sit 15–30 min (baking soda) or 30 min (egg white). Rinse baking soda method beef before cooking.",
      "Cook jasmine rice. Set aside.",
      "Blanch broccoli in salted boiling water 2 min, drain. Or stir-fry in oil 3–4 min.",
      "Mix sauce: soy sauce, oyster sauce, hoisin, brown sugar, cornstarch, and sesame oil.",
      "Heat wok or heavy skillet over very high heat. Add oil. Sear beef in batches — do not crowd — 1–2 min until browned. Remove.",
      "Add garlic and ginger, 30 seconds. Add broccoli. Pour in sauce. Return beef. Toss everything 1 min until sauce is glossy and thickened. Serve over rice.",
    ],
    notes: "Baking soda velveting is faster (15 min, requires rinsing). Egg white is more traditional (30 min, better texture). High heat is non-negotiable.",
  },
  {
    id: "taco-salad",
    title: "Taco Salad with Valentina and Ranch Doritos",
    tags: ["Weeknight", "Mexican", "30 min"],
    time: 25,
    servings: 4,
    ingredients: [
      { amount: 1, unit: "lb", item: "ground beef (80/20)" },
      { amount: 2, unit: "tbsp", item: "taco seasoning" },
      { amount: 1, unit: "head", item: "romaine lettuce, chopped" },
      { amount: 1, unit: "can", item: "black beans, drained and rinsed (15 oz)" },
      { amount: 1, unit: "cup", item: "cherry tomatoes, halved" },
      { amount: 1, unit: "cup", item: "shredded Mexican cheese blend" },
      { amount: 0.5, unit: "cup", item: "sour cream" },
      { amount: 0.5, unit: "cup", item: "guacamole or sliced avocado" },
      { amount: "", unit: "", item: "Valentina hot sauce, to taste — essential" },
      { amount: 1, unit: "bag", item: "Ranch Doritos, crushed" },
      { amount: "", unit: "", item: "Optional: salsa, jalapeño, cilantro" },
    ],
    steps: [
      "Brown ground beef in a skillet over medium-high. Drain fat. Add taco seasoning and a splash of water. Cook 2 min until saucy.",
      "Build bowls: romaine as the base, then warm beef, black beans, tomatoes, cheese, guacamole, and sour cream.",
      "Hit with Valentina hot sauce.",
      "Crush Ranch Doritos and scatter on top right before serving so they stay crunchy.",
    ],
    notes: "Doritos go on last — they go soggy fast. Valentina is essential.",
  },

  // ── NEW RECIPES ──────────────────────────────────────────────────────────────

  {
    id: "fish-tacos",
    title: "Fish Tacos with Chipotle Crema",
    tags: ["Weeknight", "Mexican", "Seafood", "30 min"],
    time: 30,
    servings: 4,
    ingredients: [
      { amount: 1.5, unit: "lbs", item: "halibut or cod fillets, cut into strips" },
      { amount: 8, unit: "", item: "corn tortillas" },
      { amount: 1, unit: "tsp", item: "chili powder" },
      { amount: 1, unit: "tsp", item: "cumin" },
      { amount: 1, unit: "tsp", item: "garlic powder" },
      { amount: 0.5, unit: "tsp", item: "smoked paprika" },
      { amount: 2, unit: "tbsp", item: "neutral oil" },
      { amount: "", unit: "", item: "— Chipotle Crema —" },
      { amount: 0.5, unit: "cup", item: "sour cream" },
      { amount: 1, unit: "tbsp", item: "chipotle in adobo, minced (plus sauce from can)" },
      { amount: 1, unit: "", item: "lime, juiced" },
      { amount: 1, unit: "clove", item: "garlic, grated" },
      { amount: "", unit: "", item: "— Quick Slaw —" },
      { amount: 2, unit: "cups", item: "green cabbage, finely shredded" },
      { amount: 2, unit: "tbsp", item: "apple cider vinegar" },
      { amount: 1, unit: "tbsp", item: "olive oil" },
      { amount: 1, unit: "tsp", item: "honey" },
      { amount: "", unit: "", item: "— Toppings —" },
      { amount: 1, unit: "", item: "avocado, sliced" },
      { amount: 0.5, unit: "cup", item: "fresh cilantro" },
      { amount: "", unit: "", item: "Lime wedges, Valentina or hot sauce" },
    ],
    steps: [
      "Make chipotle crema: combine sour cream, minced chipotle with adobo sauce, lime juice, and grated garlic. Stir well. Refrigerate until ready to serve.",
      "Make quick slaw: toss shredded cabbage with apple cider vinegar, olive oil, honey, and a pinch of salt. Let sit while you cook the fish.",
      "Season fish strips with chili powder, cumin, garlic powder, smoked paprika, salt, and pepper.",
      "Heat oil in a skillet over medium-high. Cook fish in batches 2–3 min per side until flaky and golden. Don't crowd the pan.",
      "Warm corn tortillas directly over a gas flame or in a dry skillet.",
      "Build tacos: tortilla → slaw → fish → chipotle crema → avocado → cilantro → squeeze of lime. Add hot sauce.",
    ],
    notes: "Halibut preferred. Fish cooks fast — don't overcook. Crema can be made 2 days ahead. Slaw is best fresh.",
  },
  {
    id: "falafel-pita",
    title: "Falafel Pita with Tzatziki and Green Goddess",
    tags: ["Lighter Fare", "Vegetarian"],
    time: 40,
    servings: 4,
    ingredients: [
      { amount: "", unit: "", item: "— Falafel —" },
      { amount: 2, unit: "cans", item: "chickpeas, drained and very dry (15 oz each)" },
      { amount: 0.5, unit: "cup", item: "fresh parsley" },
      { amount: 0.5, unit: "cup", item: "fresh cilantro" },
      { amount: 4, unit: "cloves", item: "garlic" },
      { amount: 1, unit: "", item: "small onion, roughly chopped" },
      { amount: 1, unit: "tsp", item: "cumin" },
      { amount: 1, unit: "tsp", item: "coriander" },
      { amount: 0.5, unit: "tsp", item: "cayenne" },
      { amount: 3, unit: "tbsp", item: "all-purpose flour" },
      { amount: 1, unit: "tsp", item: "baking powder" },
      { amount: 3, unit: "tbsp", item: "neutral oil (for frying)" },
      { amount: "", unit: "", item: "— Tzatziki —" },
      { amount: 1, unit: "cup", item: "plain Greek yogurt" },
      { amount: 0.5, unit: "", item: "English cucumber, grated and squeezed dry" },
      { amount: 2, unit: "cloves", item: "garlic, grated" },
      { amount: 1, unit: "tbsp", item: "fresh dill" },
      { amount: 1, unit: "tbsp", item: "lemon juice" },
      { amount: "", unit: "", item: "— Assembly —" },
      { amount: 4, unit: "", item: "pita breads" },
      { amount: 1, unit: "cup", item: "cherry tomatoes, halved" },
      { amount: 0.5, unit: "", item: "English cucumber, diced" },
      { amount: 0.5, unit: "", item: "red onion, thinly sliced" },
      { amount: "", unit: "", item: "Green goddess dressing (store-bought or homemade)" },
    ],
    steps: [
      "Make tzatziki: combine Greek yogurt, grated cucumber (squeezed dry), garlic, dill, and lemon juice. Season with salt. Refrigerate.",
      "Make falafel: pulse chickpeas, parsley, cilantro, onion, garlic, cumin, coriander, and cayenne in a food processor until a coarse paste forms — not smooth. Transfer to a bowl. Stir in flour, baking powder, and 1 tsp salt. Mixture should hold when pressed.",
      "Form into small patties or balls, about 2 tbsp each.",
      "Heat oil in a skillet over medium-high. Fry falafel in batches 3–4 min per side until deeply golden and crispy. Don't flip too early.",
      "Warm pitas briefly in the oven or over a flame.",
      "Assemble: open pita, spread tzatziki, add 3–4 falafel, top with tomato, cucumber, red onion, and a drizzle of green goddess.",
    ],
    notes: "Do not over-process chickpeas — coarse texture is key for crust and structure. Chickpeas must be completely dry. Falafel mixture can be made a day ahead. Tzatziki holds 3 days.",
  },
  {
    id: "tuna-avocado-toast",
    title: "Tuna Avocado Toast",
    tags: ["Lighter Fare", "Quick", "30 min"],
    time: 15,
    servings: 2,
    ingredients: [
      { amount: 2, unit: "cans", item: "solid white albacore tuna in water, drained (5 oz each)" },
      { amount: 2, unit: "", item: "ripe avocados" },
      { amount: 4, unit: "slices", item: "thick sourdough or multigrain bread, toasted" },
      { amount: 2, unit: "tbsp", item: "mayonnaise" },
      { amount: 1, unit: "tbsp", item: "Dijon mustard" },
      { amount: 1, unit: "tbsp", item: "capers, roughly chopped" },
      { amount: 1, unit: "", item: "lemon, juiced" },
      { amount: 0.25, unit: "cup", item: "red onion, finely diced" },
      { amount: 1, unit: "tsp", item: "everything bagel seasoning" },
      { amount: "", unit: "", item: "Red pepper flakes, salt, pepper" },
      { amount: "", unit: "", item: "Optional: sliced radish, arugula, cucumber" },
    ],
    steps: [
      "Mix tuna with mayo, Dijon, capers, half the lemon juice, and red onion. Season with salt and pepper. Taste and adjust.",
      "Halve and pit avocados. Scoop flesh into a bowl. Add remaining lemon juice and a pinch of salt. Mash to desired texture — leave some chunks.",
      "Toast bread until deeply golden.",
      "Spread avocado on toast. Top with tuna mixture. Sprinkle with everything bagel seasoning and red pepper flakes.",
      "Add optional toppings. Serve immediately.",
    ],
    notes: "Eat promptly — toasted bread softens quickly. Tuna mixture can be made ahead and refrigerated up to 2 days.",
  },
  {
    id: "chicken-pot-pie-casserole",
    title: "Chicken Pot Pie Casserole",
    tags: ["Weeknight", "Chicken", "Comfort Food", "Make-Ahead"],
    time: 55,
    servings: 6,
    ingredients: [
      { amount: 2, unit: "lbs", item: "boneless skinless chicken thighs — or rotisserie chicken, shredded" },
      { amount: 1, unit: "cup", item: "frozen peas" },
      { amount: 1, unit: "cup", item: "frozen corn" },
      { amount: 2, unit: "", item: "medium carrots, diced" },
      { amount: 2, unit: "stalks", item: "celery, diced" },
      { amount: 1, unit: "", item: "medium yellow onion, diced" },
      { amount: 3, unit: "cloves", item: "garlic, minced" },
      { amount: 3, unit: "tbsp", item: "butter" },
      { amount: 3, unit: "tbsp", item: "all-purpose flour" },
      { amount: 2, unit: "cups", item: "chicken stock (Better Than Bouillon)" },
      { amount: 0.75, unit: "cup", item: "whole milk or cream" },
      { amount: 1, unit: "tsp", item: "dried thyme" },
      { amount: 1, unit: "tsp", item: "dried rosemary" },
      { amount: 1, unit: "tube", item: "refrigerated biscuit dough (8-count) or 1 sheet puff pastry" },
      { amount: 1, unit: "", item: "egg, beaten (for egg wash)" },
      { amount: "", unit: "", item: "Salt, pepper" },
    ],
    steps: [
      "Preheat oven to 400°F. If using raw chicken, poach or bake at 400°F for 20 min until cooked through. Shred and set aside.",
      "In a large oven-safe skillet or Dutch oven, melt butter over medium. Sauté onion, carrot, and celery 5–6 min until softened. Add garlic 30 seconds.",
      "Sprinkle flour over vegetables. Stir 1–2 min. Slowly pour in chicken stock and milk, stirring constantly. Bring to a simmer until thickened, 3–4 min.",
      "Add thyme, rosemary, peas, corn, and shredded chicken. Season generously with salt and pepper. Taste and adjust.",
      "Remove from heat. Top filling with biscuit rounds (slightly overlapping) or puff pastry. Brush with egg wash.",
      "Bake 22–25 min until topping is deep golden brown and filling is bubbling at the edges. Rest 5 min before serving.",
    ],
    notes: "Make-ahead: prepare filling up to 2 days ahead, refrigerate. Add biscuit topping just before baking. Rotisserie chicken is the weeknight shortcut. Freezes well without the biscuit topping.",
  },
  {
    id: "homemade-pita",
    title: "Homemade Pita Bread",
    tags: ["Side", "Bread"],
    time: 90,
    servings: 8,
    ingredients: [
      { amount: 3, unit: "cups", item: "all-purpose flour, plus more for dusting" },
      { amount: 1, unit: "packet", item: "instant yeast (2¼ tsp)" },
      { amount: 1, unit: "cup", item: "warm water (110°F)" },
      { amount: 1, unit: "tsp", item: "sugar" },
      { amount: 1.5, unit: "tsp", item: "salt" },
      { amount: 2, unit: "tbsp", item: "olive oil" },
    ],
    steps: [
      "Combine warm water, sugar, and yeast. Let sit 5 min until foamy.",
      "In a large bowl, mix flour and salt. Add yeast mixture and olive oil. Stir until dough comes together.",
      "Knead on a floured surface 8–10 min until smooth and elastic. Or use a stand mixer with dough hook on medium 6–7 min.",
      "Place dough in an oiled bowl, cover with a damp towel. Let rise 1 hour until doubled.",
      "Punch down. Divide into 8 equal portions. Roll each into a smooth ball, then roll flat to about ⅛ inch thick and roughly 6 inches across.",
      "Heat a dry cast iron skillet or heavy pan over high heat until very hot. Cook each pita 1–2 min per side until it puffs and gets golden spots. Wrap in a clean towel immediately to keep soft.",
    ],
    notes: "The pocket forms when the pita puffs from steam. Stack and wrap in a towel right off the pan. Freeze extras and reheat wrapped in damp paper towels in microwave 30 seconds.",
  },
  {
    id: "instant-pot-cheddar-grits",
    title: "Instant Pot Cheddar Grits",
    tags: ["Side"],
    time: 25,
    servings: 4,
    ingredients: [
      { amount: 1, unit: "cup", item: "stone-ground grits (not instant)" },
      { amount: 3, unit: "cups", item: "water" },
      { amount: 1, unit: "cup", item: "chicken stock (Better Than Bouillon)" },
      { amount: 1.5, unit: "cups", item: "shredded sharp cheddar" },
      { amount: 3, unit: "tbsp", item: "butter" },
      { amount: 0.5, unit: "cup", item: "whole milk or cream (added after cooking)" },
      { amount: 1, unit: "tsp", item: "salt" },
      { amount: 0.5, unit: "tsp", item: "white pepper or black pepper" },
      { amount: "", unit: "", item: "Optional: pinch of cayenne, hot sauce" },
    ],
    steps: [
      "Add grits, water, stock, and salt to the Instant Pot. Stir to combine.",
      "Lock lid, valve to sealing. Cook on High Pressure 10 minutes.",
      "Natural release 10 min, then carefully quick release remaining pressure.",
      "Open lid and stir — grits will look thin at first but thicken quickly.",
      "Add butter and shredded cheddar. Stir until fully melted and incorporated.",
      "Stir in milk or cream to reach desired consistency. Season with pepper and cayenne. Serve immediately.",
    ],
    notes: "Grits thicken significantly as they cool — serve promptly or reheat with a splash of water or milk. Stone-ground only — instant grits turn to mush under pressure. These are the base for the Seared Scallops dish.",
  },
];
